In [30]:
import numpy as np

In [31]:
arr = np.array([[3,65,45,78]], np.int64)

In [32]:
arr

array([[ 3, 65, 45, 78]], dtype=int64)

In [33]:
arr.shape

(1, 4)

In [34]:
arr[0,1]

65

# Array Creation : conversion from other Python structures

In [38]:
listarray = np.array([[1,2,3],[5,6,7],[8,9,0]])

In [39]:
listarray

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 0]])

In [40]:
listarray.dtype

dtype('int32')

In [42]:
listarray.shape

(3, 3)

In [43]:
listarray.size

9

In [44]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [45]:
zeros = np.zeros((2,5))

In [46]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
rng = np.arange(15)

In [48]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
lspace = np.linspace(1,4,4)

In [54]:
lspace

array([1., 2., 3., 4.])

In [55]:
emp = np.empty((4,6))

In [56]:
emp

array([[6.95225375e-310, 6.95225374e-310, 0.00000000e+000,
        0.00000000e+000, 8.15221967e-312, 4.94065646e-324],
       [0.00000000e+000, 0.00000000e+000, 4.04738577e-320,
        0.00000000e+000, 1.23022346e-321, 8.15445427e-312],
       [1.33511969e-306, 1.78022342e-306, 0.00000000e+000,
        8.15445445e-312, 1.69118108e-306, 8.06632139e-308],
       [1.20160711e-306, 4.79243676e-322, 1.29062229e-306,
        6.89804133e-307, 1.11261162e-306,             nan]])

In [57]:
ide = np.identity(45)

In [58]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [59]:
arrr = np.arange(99)

In [60]:
arrr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [61]:
arrr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [66]:
arrr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [63]:
arrr = arrr.reshape(3,33)

In [64]:
arrr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [67]:
arrr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [68]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [69]:
ar = np.array(x)

In [70]:
ar.sum(axis=0)

array([12,  8,  9])

In [71]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [72]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [73]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [74]:
ar.flat

In [75]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [76]:
ar.ndim 

2

In [77]:
ar.size

9

In [78]:
ar.nbytes

36

In [83]:
one = np.array([1,3,4,634,2])

In [84]:
one.argmax()

3

In [85]:
one.argmin()

0

In [86]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [87]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [88]:
ar.argmin()

8

In [89]:
ar.argmax()

6

In [90]:
ar.argmax(axis =0)

array([2, 1, 1], dtype=int64)

In [91]:
ar.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [92]:
ar2 = [[34,45,56],[67,78,89],[12,23,34]]

In [93]:
ar2


[[34, 45, 56], [67, 78, 89], [12, 23, 34]]

In [94]:
ar + ar2

array([[35, 47, 59],
       [71, 83, 95],
       [19, 24, 34]])

In [95]:
ar.sum()

29

In [96]:
ar.min()

0

In [97]:
ar.max()

7

In [98]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [99]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))